// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrhj8YtuhUCYbHlqnHKjNlob7FOy5DxjM',
    appId: '1:873942598551:web:197e56d6313d2442867ad2',
    messagingSenderId: '873942598551',
    projectId: 'zpy-user-management',
    authDomain: 'zpy-user-management.firebaseapp.com',
    storageBucket: 'zpy-user-management.appspot.com',
    measurementId: 'G-DF9F4R05K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO9QYOta4eXha090d-kHjMld7FhvE15NQ',
    appId: '1:873942598551:android:eafda0133c2d6768867ad2',
    messagingSenderId: '873942598551',
    projectId: 'zpy-user-management',
    storageBucket: 'zpy-user-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaxT-rZ8K_lQ6D1h23nhFUPywL3hTBN88',
    appId: '1:873942598551:ios:ca7fff302c637ccc867ad2',
    messagingSenderId: '873942598551',
    projectId: 'zpy-user-management',
    storageBucket: 'zpy-user-management.appspot.com',
    iosClientId: '873942598551-87iqie5m8912itetg9m6kru4h88ei9km.apps.googleusercontent.com',
    iosBundleId: 'com.example.userFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaxT-rZ8K_lQ6D1h23nhFUPywL3hTBN88',
    appId: '1:873942598551:ios:dfd9808e381f0275867ad2',
    messagingSenderId: '873942598551',
    projectId: 'zpy-user-management',
    storageBucket: 'zpy-user-management.appspot.com',
    iosClientId: '873942598551-n5224kovsdvna419tev2o2ag9as0ak01.apps.googleusercontent.com',
    iosBundleId: 'com.example.userFirebase.RunnerTests',
  );
}
